/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.generator;

import fr.inria.diverse.k3.al.annotationprocessor.Aspect;
import fr.inria.diverse.k3.al.annotationprocessor.Step;
import stateMachine.State;

@Aspect(className = State.class)
@SuppressWarnings("all")
public class StateAspect {
  @Step
  public String step(final String inputString) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field _self is undefined"
      + "\nThe method or field name is undefined for the type Object"
      + "\nThere is no context to infer the closure\'s argument types from. Consider typing the arguments or put the closures into a typed context."
      + "\noutgoing cannot be resolved"
      + "\nfilter cannot be resolved"
      + "\nsize cannot be resolved"
      + "\n> cannot be resolved"
      + "\nget cannot be resolved"
      + "\nfire cannot be resolved");
  }
}
