/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.generator;

import fr.inria.diverse.k3.al.annotationprocessor.Aspect;
import fr.inria.diverse.k3.al.annotationprocessor.Step;
import stateMachine.Transition;

@Aspect(className = Transition.class)
@SuppressWarnings("all")
public class TransitionAspect {
  @Step
  public String fire() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field _self is undefined"
      + "\nThe method or field _self is undefined"
      + "\nThe method or field _self is undefined"
      + "\nThe method or field _self is undefined"
      + "\nThe method or field _self is undefined"
      + "\norigine cannot be resolved"
      + "\nname cannot be resolved"
      + "\ntarget cannot be resolved"
      + "\nname cannot be resolved"
      + "\norigine cannot be resolved"
      + "\ncurrentState cannot be resolved"
      + "\ntarget cannot be resolved"
      + "\nname cannot be resolved");
  }
}
